{"metadata":{"role":"symbol","modules":[{"name":"SotoCore"}],"symbolKind":"property","externalID":"s:8SotoCore14AWSServerErrorV7contextAA15AWSErrorContextVSgvp","title":"context","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","kind":"typeIdentifier","text":"AWSErrorContext"},{"text":"?","kind":"text"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsservererror\/context"]}],"kind":"symbol","identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","interfaceLanguage":"swift"},"abstract":[{"text":"additional context information related to the error","type":"text"}],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"kind":"text","text":"?"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/context":{"url":"\/documentation\/sotocore\/awsservererror\/context","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"context"},{"text":": ","kind":"text"},{"text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","title":"context","abstract":[{"type":"text","text":"additional context information related to the error"}],"role":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"navigatorTitle":[{"kind":"identifier","text":"AWSErrorContext"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AWSErrorContext","kind":"identifier"}],"url":"\/documentation\/sotocore\/awserrorcontext","abstract":[{"text":"Additional information about error","type":"text"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","type":"topic","title":"AWSErrorContext","kind":"symbol","role":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore":{"abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"kind":"symbol","url":"\/documentation\/sotocore","type":"topic","role":"collection","title":"SotoCore","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","navigatorTitle":[{"kind":"identifier","text":"AWSServerError"}],"url":"\/documentation\/sotocore\/awsservererror","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AWSServerError","kind":"identifier"}],"role":"symbol","title":"AWSServerError","kind":"symbol"}}}