{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsservererror\/init(errorcode:context:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/init(errorCode:context:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"init","role":"symbol","title":"init(errorCode:context:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"errorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"text":")","kind":"text"}],"modules":[{"name":"SotoCore"}],"roleHeading":"Initializer","externalID":"s:8SotoCore14AWSServerErrorV9errorCode7contextACSgSS_AA15AWSErrorContextVtcfc"},"kind":"symbol","sections":[],"abstract":[{"text":"initialize AWSServerError","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"text":"errorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AWSErrorContext","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["macOS"]}]}],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"kind":"symbol","url":"\/documentation\/sotocore","type":"topic","role":"collection","title":"SotoCore","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","navigatorTitle":[{"kind":"identifier","text":"AWSServerError"}],"url":"\/documentation\/sotocore\/awsservererror","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AWSServerError","kind":"identifier"}],"role":"symbol","title":"AWSServerError","kind":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"navigatorTitle":[{"kind":"identifier","text":"AWSErrorContext"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AWSErrorContext","kind":"identifier"}],"url":"\/documentation\/sotocore\/awserrorcontext","abstract":[{"text":"Additional information about error","type":"text"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","type":"topic","title":"AWSErrorContext","kind":"symbol","role":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/init(errorCode:context:)":{"role":"symbol","title":"init(errorCode:context:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"errorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"context"},{"text":": ","kind":"text"},{"text":"AWSErrorContext","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"initialize AWSServerError"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/init(errorCode:context:)","url":"\/documentation\/sotocore\/awsservererror\/init(errorcode:context:)"}}}