{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","kind":"typeIdentifier","text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"metadata":{"externalID":"s:8SotoCore16AWSResponseErrorV7contextAA15AWSErrorContextVSgvp","symbolKind":"property","role":"symbol","modules":[{"name":"SotoCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","text":"AWSErrorContext","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"context"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/context"},"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsresponseerror\/context"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"additional context information related to the error","type":"text"}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","url":"\/documentation\/sotocore","kind":"symbol","title":"SotoCore","abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"type":"topic","role":"collection"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWSResponseError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AWSResponseError"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError","kind":"symbol","url":"\/documentation\/sotocore\/awsresponseerror","type":"topic","title":"AWSResponseError","role":"symbol","abstract":[{"text":"Response Error type returned by Soto if the error code is unrecognised","type":"text"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"url":"\/documentation\/sotocore\/awserrorcontext","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","kind":"symbol","abstract":[{"text":"Additional information about error","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AWSErrorContext","kind":"identifier"}],"title":"AWSErrorContext","type":"topic","navigatorTitle":[{"text":"AWSErrorContext","kind":"identifier"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError/context":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"context"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV","text":"AWSErrorContext"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/context","kind":"symbol","url":"\/documentation\/sotocore\/awsresponseerror\/context","type":"topic","title":"context","role":"symbol","abstract":[{"text":"additional context information related to the error","type":"text"}]}}}