{"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy"]]},"metadata":{"title":"getRetryWaitTime(error:attempt:)","symbolKind":"method","role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getRetryWaitTime","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":", "},{"text":"attempt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"text":"RetryStatus","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore11RetryStatusO"},{"kind":"text","text":"?"}],"externalID":"s:8SotoCore11RetryPolicyP03getC8WaitTime5error7attemptAA0C6StatusOSgs5Error_p_SitF","modules":[{"name":"SotoCore"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getRetryWaitTime","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attempt"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"text":"RetryStatus","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryStatus","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore11RetryStatusO"},{"kind":"text","text":"?"}],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error returned by HTTP client"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Retry attempt number"}],"type":"paragraph"}],"name":"attempt"}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Returns whether we should retry and how long we should wait before retrying"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy\/getRetryWaitTime(error:attempt:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/retrypolicy\/getretrywaittime(error:attempt:)"]}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","url":"\/documentation\/sotocore","kind":"symbol","title":"SotoCore","abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"type":"topic","role":"collection"},"doc://codes.soto.soto-core/documentation/SotoCore/RetryPolicy":{"abstract":[{"type":"text","text":"Protocol for Retry strategy. Has function returning amount of time before the next retry after an HTTP error"}],"url":"\/documentation\/sotocore\/retrypolicy","title":"RetryPolicy","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RetryPolicy"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy","navigatorTitle":[{"text":"RetryPolicy","kind":"identifier"}]},"doc://codes.soto.soto-core/documentation/SotoCore/RetryPolicy/getRetryWaitTime(error:attempt:)":{"abstract":[{"type":"text","text":"Returns whether we should retry and how long we should wait before retrying"}],"url":"\/documentation\/sotocore\/retrypolicy\/getretrywaittime(error:attempt:)","type":"topic","required":true,"role":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy\/getRetryWaitTime(error:attempt:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getRetryWaitTime","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"attempt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":") -> ","kind":"text"},{"text":"RetryStatus","preciseIdentifier":"s:8SotoCore11RetryStatusO","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"getRetryWaitTime(error:attempt:)"},"doc://codes.soto.soto-core/documentation/SotoCore/RetryStatus":{"abstract":[{"type":"text","text":"Return value for "},{"type":"codeVoice","code":"RetryPolicy.getRetryWaitTime"},{"type":"text","text":". Either retry after time amount or donâ€™t retry"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RetryStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RetryStatus"}],"url":"\/documentation\/sotocore\/retrystatus","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryStatus","kind":"symbol","title":"RetryStatus","role":"symbol","type":"topic"}}}