{"metadata":{"modules":[{"name":"SotoCore"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"waiterFailed","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV","kind":"typeIdentifier","text":"ClientError"}],"title":"waiterFailed","role":"symbol","symbolKind":"property","externalID":"s:8SotoCore9AWSClientC11ClientErrorV12waiterFailedAEvpZ","roleHeading":"Type Property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/sotocore\/awsclient\/clienterror\/waiterfailed"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Waiter failed, but without an error. ie a successful api call was an error"}],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError\/waiterFailed","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"waiterFailed","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClientError","preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient":{"url":"\/documentation\/sotocore\/awsclient","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Client managing communication with AWS services"}],"navigatorTitle":[{"text":"AWSClient","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AWSClient","kind":"identifier"}],"title":"AWSClient"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient/ClientError":{"title":"AWSClient.ClientError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientError"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ClientError","kind":"identifier"}],"url":"\/documentation\/sotocore\/awsclient\/clienterror","role":"symbol","abstract":[{"type":"text","text":"Errors returned by "},{"code":"AWSClient","type":"codeVoice"},{"text":" code","type":"text"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient/ClientError/waiterFailed":{"url":"\/documentation\/sotocore\/awsclient\/clienterror\/waiterfailed","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waiterFailed"},{"text":": ","kind":"text"},{"text":"ClientError","preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV","kind":"typeIdentifier"}],"kind":"symbol","title":"waiterFailed","abstract":[{"type":"text","text":"Waiter failed, but without an error. ie a successful api call was an error"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError\/waiterFailed"},"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","role":"collection","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","kind":"symbol","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"url":"\/documentation\/sotocore","title":"SotoCore"}}}