{"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError"]]},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waiterFailed"},{"text":": ","kind":"text"},{"text":"ClientError","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV"}],"role":"symbol","title":"waiterFailed","externalID":"s:8SotoCore9AWSClientC11ClientErrorV12waiterFailedAEvpZ","roleHeading":"Type Property","modules":[{"name":"SotoCore"}],"symbolKind":"property"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsclient\/clienterror\/waiterfailed"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"waiterFailed","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError","preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV","text":"ClientError"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError\/waiterFailed","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Waiter failed, but without an error. ie a successful api call was an error","type":"text"}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient/ClientError/waiterFailed":{"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError\/waiterFailed","abstract":[{"type":"text","text":"Waiter failed, but without an error. ie a successful api call was an error"}],"type":"topic","url":"\/documentation\/sotocore\/awsclient\/clienterror\/waiterfailed","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waiterFailed"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV","text":"ClientError","kind":"typeIdentifier"}],"role":"symbol","title":"waiterFailed"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient/ClientError":{"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError","abstract":[{"type":"text","text":"Errors returned by "},{"type":"codeVoice","code":"AWSClient"},{"text":" code","type":"text"}],"url":"\/documentation\/sotocore\/awsclient\/clienterror","type":"topic","title":"AWSClient.ClientError","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ClientError"}],"navigatorTitle":[{"text":"ClientError","kind":"identifier"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient":{"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient","abstract":[{"text":"Client managing communication with AWS services","type":"text"}],"url":"\/documentation\/sotocore\/awsclient","type":"topic","title":"AWSClient","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AWSClient"}],"navigatorTitle":[{"kind":"identifier","text":"AWSClient"}]},"doc://codes.soto.soto-core/documentation/SotoCore":{"abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","title":"SotoCore","url":"\/documentation\/sotocore","role":"collection","type":"topic"}}}