{"variants":[{"paths":["\/documentation\/sotocore\/awsclient\/clienterror\/waiterfailed"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Waiter failed, but without an error. ie a successful api call was an error","type":"text"}],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waiterFailed"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError","text":"ClientError","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","title":"waiterFailed","roleHeading":"Type Property","role":"symbol","externalID":"s:8SotoCore9AWSClientC11ClientErrorV12waiterFailedAEvpZ","modules":[{"name":"SotoCore"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"waiterFailed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ClientError","preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV","kind":"typeIdentifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError\/waiterFailed"},"kind":"symbol","references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","url":"\/documentation\/sotocore","title":"SotoCore","role":"collection"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient/ClientError":{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ClientError","kind":"identifier"}],"title":"AWSClient.ClientError","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ClientError"}],"type":"topic","url":"\/documentation\/sotocore\/awsclient\/clienterror","abstract":[{"type":"text","text":"Errors returned by "},{"code":"AWSClient","type":"codeVoice"},{"text":" code","type":"text"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient/ClientError/waiterFailed":{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError\/waiterFailed","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"waiterFailed"},{"text":": ","kind":"text"},{"text":"ClientError","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV"}],"kind":"symbol","title":"waiterFailed","abstract":[{"text":"Waiter failed, but without an error. ie a successful api call was an error","type":"text"}],"role":"symbol","url":"\/documentation\/sotocore\/awsclient\/clienterror\/waiterfailed"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient":{"abstract":[{"type":"text","text":"Client managing communication with AWS services"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AWSClient","kind":"identifier"}],"role":"symbol","url":"\/documentation\/sotocore\/awsclient","kind":"symbol","title":"AWSClient","navigatorTitle":[{"text":"AWSClient","kind":"identifier"}],"type":"topic"}}}