{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRetryWaitTime"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attempt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryStatus","preciseIdentifier":"s:8SotoCore11RetryStatusO","text":"RetryStatus"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error returned by HTTP client"}]}]},{"name":"attempt","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"retry attempt number"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sotocore\/retrypolicy\/getretrywaittime(error:attempt:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy\/getRetryWaitTime(error:attempt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns whether we should retry and how long we should wait before retrying"}],"kind":"symbol","metadata":{"role":"symbol","title":"getRetryWaitTime(error:attempt:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRetryWaitTime"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attempt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"RetryStatus","preciseIdentifier":"s:8SotoCore11RetryStatusO"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"s:8SotoCore11RetryPolicyP03getC8WaitTime5error7attemptAA0C6StatusOSgs5Error_p_SitF","required":true,"modules":[{"name":"SotoCore"}]},"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy"]]},"references":{"doc://codes.soto.soto-core/documentation/SotoCore/RetryStatus":{"role":"symbol","title":"RetryStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RetryStatus"}],"abstract":[{"type":"text","text":"Return value for "},{"type":"codeVoice","code":"RetryPolicy.getRetryWaitTime"},{"type":"text","text":". Either retry after time amount or donâ€™t retry"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RetryStatus"}],"url":"\/documentation\/sotocore\/retrystatus"},"doc://codes.soto.soto-core/documentation/SotoCore/RetryPolicy":{"role":"symbol","title":"RetryPolicy","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RetryPolicy"}],"abstract":[{"type":"text","text":"Protocol for Retry strategy. Has function returning amount of time before the next retry after an HTTP error"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RetryPolicy"}],"url":"\/documentation\/sotocore\/retrypolicy"},"doc://codes.soto.soto-core/documentation/SotoCore":{"role":"collection","title":"SotoCore","abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","kind":"symbol","type":"topic","url":"\/documentation\/sotocore"},"doc://codes.soto.soto-core/documentation/SotoCore/RetryPolicy/getRetryWaitTime(error:attempt:)":{"role":"symbol","title":"getRetryWaitTime(error:attempt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRetryWaitTime"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attempt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"RetryStatus","preciseIdentifier":"s:8SotoCore11RetryStatusO"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns whether we should retry and how long we should wait before retrying"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/RetryPolicy\/getRetryWaitTime(error:attempt:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sotocore\/retrypolicy\/getretrywaittime(error:attempt:)"}}}